version: "3.4"

services:
  store-db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-phamtuandat1a0}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
    hostname: postgres-host

volumes:
  pgdata:
networks:
  postgres:
    driver: bridge
